{-
   pgtune
   A service to generate some optimized configuration parameters for PostgreSQL based on best practices.

   The version of the OpenAPI document: 1.0
   Contact: sainth@sainth.de

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Request.Default exposing (generateConfiguration)

import Data.SystemConfiguration as SystemConfiguration exposing (SystemConfiguration)
import Dict
import Http
import Json.Decode as Decode
import Url.Builder as Url




basePath : String
basePath =
    "http://localhost"


generateConfiguration :
    { onSend : Result Http.Error String -> msg


    , body : SystemConfiguration


    }
    -> Cmd msg
generateConfiguration params =
    Http.request
        { method = "POST"
        , headers = []
        , url = Url.crossOrigin basePath
            ["configuration"]
            []
        , body = Http.jsonBody <| SystemConfiguration.encode params.body
        , expect = Http.expectJson params.onSend Decode.string
        , timeout = Just 30000
        , tracker = Nothing
        }
