{-
   pgtune
   A service to generate some optimized configuration parameters for PostgreSQL based on best practices.

   The version of the OpenAPI document: 1.0
   Contact: sainth@sainth.de

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.DbApplication exposing (DbApplication(..), decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type DbApplication
    = WEB
    | OLTP
    | DATAWAREHOUSE
    | DESKTOP
    | MIXED


decoder : Decoder DbApplication
decoder =
    Decode.string
        |> Decode.andThen
            (\str ->
                case str of
                    "WEB" ->
                        Decode.succeed WEB

                    "OLTP" ->
                        Decode.succeed OLTP

                    "DATA_WAREHOUSE" ->
                        Decode.succeed DATAWAREHOUSE

                    "DESKTOP" ->
                        Decode.succeed DESKTOP

                    "MIXED" ->
                        Decode.succeed MIXED

                    other ->
                        Decode.fail <| "Unknown type: " ++ other
            )


encode : DbApplication -> Encode.Value
encode model =
    case model of
        WEB ->
            Encode.string "WEB"

        OLTP ->
            Encode.string "OLTP"

        DATAWAREHOUSE ->
            Encode.string "DATA_WAREHOUSE"

        DESKTOP ->
            Encode.string "DESKTOP"

        MIXED ->
            Encode.string "MIXED"
