{-
   pgtune
   A service to generate some optimized configuration parameters for PostgreSQL based on best practices.

   The version of the OpenAPI document: 1.0
   Contact: sainth@sainth.de

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.Memory exposing (Memory, decoder, encode)

import Data.SizeUnit as SizeUnit exposing (SizeUnit)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias Memory =
    { memory : Int
    , unit : SizeUnit
    }


decoder : Decoder Memory
decoder =
    Decode.succeed Memory
        |> required "memory" Decode.int
        |> required "unit" SizeUnit.decoder


encode : Memory -> Encode.Value
encode model =
    Encode.object
        [ ( "memory", Encode.int model.memory )
        , ( "unit", SizeUnit.encode model.unit )
        ]
