{-
   pgtune
   A service to generate some optimized configuration parameters for PostgreSQL based on best practices.

   The version of the OpenAPI document: 1.0
   Contact: sainth@sainth.de

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.PostgresVersion exposing (PostgresVersion(..), decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type PostgresVersion
    = V94
    | V95
    | V96
    | V10
    | V11
    | V12



decoder : Decoder PostgresVersion
decoder =
    Decode.string
        |> Decode.andThen
            (\str ->
                case str of
                    "V9_4" ->
                        Decode.succeed V94

                    "V9_5" ->
                        Decode.succeed V95

                    "V9_6" ->
                        Decode.succeed V96

                    "V10" ->
                        Decode.succeed V10

                    "V11" ->
                        Decode.succeed V11

                    "V12" ->
                        Decode.succeed V12

                    other ->
                        Decode.fail <| "Unknown type: " ++ other
            )



encode : PostgresVersion -> Encode.Value
encode model =
    case model of
        V94 ->
            Encode.string "V9_4"

        V95 ->
            Encode.string "V9_5"

        V96 ->
            Encode.string "V9_6"

        V10 ->
            Encode.string "V10"

        V11 ->
            Encode.string "V11"

        V12 ->
            Encode.string "V12"


