{-
   pgtune
   A service to generate some optimized configuration parameters for PostgreSQL based on best practices.

   The version of the OpenAPI document: 1.0
   Contact: sainth@sainth.de

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.SizeUnit exposing (SizeUnit(..), decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type SizeUnit
    = B
    | KB
    | MB
    | GB
    | TB


decoder : Decoder SizeUnit
decoder =
    Decode.string
        |> Decode.andThen
            (\str ->
                case str of
                    "B" ->
                        Decode.succeed B

                    "KB" ->
                        Decode.succeed KB

                    "MB" ->
                        Decode.succeed MB

                    "GB" ->
                        Decode.succeed GB

                    "TB" ->
                        Decode.succeed TB

                    other ->
                        Decode.fail <| "Unknown type: " ++ other
            )


encode : SizeUnit -> Encode.Value
encode model =
    case model of
        B ->
            Encode.string "B"

        KB ->
            Encode.string "KB"

        MB ->
            Encode.string "MB"

        GB ->
            Encode.string "GB"

        TB ->
            Encode.string "TB"
